"""ADP Protocol type definitions and error handling."""

from adp_hypervisor.protocol.dispatcher import Dispatcher, Handler
from adp_hypervisor.protocol.errors import (
    EXECUTION_FAILED,
    INTERNAL_ERROR,
    INVALID_PARAMS,
    INVALID_REQUEST,
    METHOD_NOT_FOUND,
    PARSE_ERROR,
    RESOURCE_NOT_FOUND,
    UNAUTHORIZED,
    VALIDATION_FAILED,
    ADPError,
    ExecutionFailedError,
    InternalError,
    InvalidParamsError,
    InvalidRequestError,
    MethodNotFoundError,
    ParseError,
    ResourceNotFoundError,
    UnauthorizedError,
    ValidationFailedError,
    error_from_code,
)
from adp_hypervisor.protocol.types import (
    JSONRPC_VERSION,
    LATEST_PROTOCOL_VERSION,
    Capabilities,
    ClientCapabilities,
    ConsistencyLevel,
    Cursor,
    DescribeRequest,
    DescribeRequestParams,
    DescribeResult,
    DiscoverFilter,
    DiscoverRequest,
    DiscoverRequestParams,
    DiscoverResult,
    EmptyResult,
    ExecuteRequest,
    ExecuteRequestParams,
    ExecuteResult,
    ExecutionMetadata,
    Field,
    FieldMetadata,
    FieldType,
    IdentityPredicate,
    Implementation,
    IngestIntent,
    InitializeRequest,
    InitializeRequestParams,
    InitializeResult,
    Intent,
    IntentClass,
    IssueSeverity,
    JSONRPCError,
    JSONRPCErrorResponse,
    JSONRPCMessage,
    JSONRPCRequest,
    JSONRPCResponse,
    JSONRPCResultResponse,
    LogicOperator,
    LookupIntent,
    MutableCapability,
    PaginatedRequestParams,
    PaginatedResult,
    PingRequest,
    Predicate,
    PredicateCapability,
    PredicateGroup,
    PredicateOperator,
    PredicateUsage,
    PredicateValue,
    ProgressToken,
    ProjectionCapability,
    QueryIntent,
    RequestId,
    RequestParams,
    Resource,
    ResourceId,
    Result,
    ReviseIntent,
    ServerCapabilities,
    SimilarValue,
    SortOrder,
    TraceId,
    UsageContract,
    ValidateRequest,
    ValidateRequestParams,
    ValidateResult,
    ValidationIssue,
    ValidationIssueCode,
)

__all__ = [
    # Constants
    "JSONRPC_VERSION",
    "LATEST_PROTOCOL_VERSION",
    # Error code constants
    "PARSE_ERROR",
    "INVALID_REQUEST",
    "METHOD_NOT_FOUND",
    "INVALID_PARAMS",
    "INTERNAL_ERROR",
    "RESOURCE_NOT_FOUND",
    "VALIDATION_FAILED",
    "UNAUTHORIZED",
    "EXECUTION_FAILED",
    # Common Types
    "RequestId",
    "ProgressToken",
    "Cursor",
    "ResourceId",
    "TraceId",
    # Enums
    "IntentClass",
    "PredicateOperator",
    "LogicOperator",
    "IssueSeverity",
    "ConsistencyLevel",
    "FieldType",
    "PredicateUsage",
    "ValidationIssueCode",
    # JSON-RPC Types
    "JSONRPCError",
    "JSONRPCRequest",
    "JSONRPCResultResponse",
    "JSONRPCErrorResponse",
    "JSONRPCResponse",
    "JSONRPCMessage",
    "RequestParams",
    "Result",
    # Predicate Types
    "SimilarValue",
    "PredicateValue",
    "Predicate",
    "IdentityPredicate",
    "PredicateGroup",
    # Initialize Types
    "Implementation",
    "ClientCapabilities",
    "ServerCapabilities",
    "InitializeRequestParams",
    "InitializeRequest",
    "InitializeResult",
    # Ping Types
    "PingRequest",
    "EmptyResult",
    # Pagination Types
    "PaginatedRequestParams",
    "PaginatedResult",
    # Discover Types
    "DiscoverFilter",
    "DiscoverRequestParams",
    "DiscoverRequest",
    "Resource",
    "DiscoverResult",
    # Describe Types
    "FieldMetadata",
    "Field",
    "PredicateCapability",
    "ProjectionCapability",
    "MutableCapability",
    "Capabilities",
    "UsageContract",
    "DescribeRequestParams",
    "DescribeRequest",
    "DescribeResult",
    # Intent Types
    "LookupIntent",
    "SortOrder",
    "QueryIntent",
    "IngestIntent",
    "ReviseIntent",
    "Intent",
    # Validate Types
    "ValidationIssue",
    "ValidateRequestParams",
    "ValidateRequest",
    "ValidateResult",
    # Execute Types
    "ExecuteRequestParams",
    "ExecuteRequest",
    "ExecutionMetadata",
    "ExecuteResult",
    # Error Classes
    "ADPError",
    "ParseError",
    "InvalidRequestError",
    "MethodNotFoundError",
    "InvalidParamsError",
    "InternalError",
    "ResourceNotFoundError",
    "ValidationFailedError",
    "UnauthorizedError",
    "ExecutionFailedError",
    "error_from_code",
    # Dispatcher
    "Dispatcher",
    "Handler",
]
