services:
  postgres:
    image: postgres:15
    container_name: adp-demo-pg
    environment:
      POSTGRES_USER: adp_user
      POSTGRES_PASSWORD: adp_pass
      POSTGRES_DB: adp_demo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-backend/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adp_user -d adp_demo"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:7
    container_name: adp-demo-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: adp_user
      MONGO_INITDB_ROOT_PASSWORD: adp_pass
      MONGO_INITDB_DATABASE: adp_demo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-backend/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5
